language: c

env:
 - RACKET_VERSION=5.3.5
 - RACKET_VERSION=5.3.6
 - RACKET_VERSION=6.0
 - RACKET_VERSION=HEAD

before_install:
# Note: Important to pipe this to `bash` not to `sh`.
- curl -L https://github.com/greghendershott/travis-racket/releases/download/v0.5/install-racket.sh | bash

install:

before_script:

script:
 - /usr/racket/bin/raco link http
 - cd http
 - /usr/racket/bin/raco make main.rkt
 - /usr/racket/bin/raco test -x .

after_script:
