language: c

env:
 - RACKET_VERSION=5.3.5

before_install:
 - curl https://raw.github.com/greghendershott/travis-racket/master/install-racket.sh | sh

install:

before_script:

script:
 - /usr/racket/bin/raco link http
 - cd http
 - /usr/racket/bin/raco make main.rkt
 - /usr/racket/bin/raco test -x .

after_script:
